#!/bin/sh
################################################################
#
# A very simple, brute-force make script for these java sources.
# Steve Mansour
################################################################
if [ ! -d "bin" ]; then
    mkdir bin
fi
if [ $# -gt 0 ]; then
    case "$1" in
	clean)	echo "cleaning..."; shift; rm bin/*.class  ;;
	*)  echo "unknown option: $1"; shift ;;
    esac
else
    javac -cp ../extern/junit-4.11.jar src/*.java -g -d bin 
fi
